TOP_URL = 'https://api.thenewsapi.com/v1/news/top/'
ALL_URL = 'https://api.thenewsapi.com/v1/news/all/'
SIMILAR_URL = 'https://api.thenewsapi.com/v1/news/similar/'
BY_UUID_URL = 'https://api.thenewsapi.com/v1/news/uuid/'
SOURCES_URL = 'https://api.thenewsapi.com/v1/news/sources/'
HEADLINES_URL = 'https://api.thenewsapi.com/v1/news/headlines/'

LOCALES = {
    "ae",
    "ar",
    "at",
    "au",
    "be",
    "bg",
    "br",
    "ca",
    "ch",
    "cn",
    "co",
    "cu",
    "cz",
    "de",
    "eg",
    "fr",
    "gb",
    "gr",
    "hk",
    "hu",
    "id",
    "ie",
    "il",
    "in",
    "it",
    "jp",
    "kr",
    "lt",
    "lv",
    "ma",
    "mx",
    "my",
    "ng",
    "nl",
    "no",
    "nz",
    "ph",
    "pl",
    "pt",
    "ro",
    "rs",
    "ru",
    "sa",
    "se",
    "sg",
    "si",
    "sk",
    "th",
    "tr",
    "tw",
    "ua",
    "us",
    "ve",
    "za",
}

DEFAULT_LANGUAGES = {
    "ae": "ar",
    "ar": "es",
    "at": "de",
    "au": "en",
    "be": "nl",
    "bg": "bg",
    "br": "pt",
    "ca": "en",
    "ch": "de",
    "cn": "zh",
    "co": "es",
    "cu": "es",
    "cz": "cs",
    "de": "de",
    "eg": "ar",
    "fr": "fr",
    "gb": "en",
    "gr": "el",
    "hk": "zh",
    "hu": "hu",
    "id": "id",
    "ie": "en",
    "il": "he",
    "in": "hi",
    "it": "it",
    "jp": "ja",
    "kr": "ko",
    "lt": "lt",
    "lv": "lv",
    "ma": "ar",
    "mx": "es",
    "my": "ms",
    "ng": "en",
    "nl": "nl",
    "no": "no",
    "nz": "en",
    "ph": "en",
    "pl": "pl",
    "pt": "pt",
    "ro": "ro",
    "rs": "sr",
    "ru": "ru",
    "sa": "ar",
    "se": "sv",
    "sg": "en",
    "si": "sl",
    "sk": "sk",
    "th": "th",
    "tr": "tr",
    "tw": "zh",
    "ua": "uk",
    "us": "en",
    "ve": "es",
    "za": "zu",
}

LANGUAGES = {"ar", "de", "en", "es", "fr", "he", "it", "nl", "no", "pt", "ru", "sv", "ud", "zh"}
FIELDS = {"title", "description", "keywords",  "main_text"}
CATEGORIES = {"general", "science", "sports", "business", "health", "entertainment", "tech", "politics", "food", "travel"}
SORTS = {"published_on","published_at","relevance_score"}
